services:
  joes:
    build:
      context: .
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3003:3003
      - 5555:5555
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=joes_cafe

volumes:
  db_data:
    name: db_data
